# Generated by Django 6.0.6 on 2026-06-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_created_at_remove_address_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10),
        ),
    ]
