# Generated by Django 6.0.6 on 2026-07-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_address_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
