# Generated by Django 6.0.6 on 2026-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
