# Generated by Django 6.0.6 on 2026-09-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
